name: Extract Keystore
on:
  workflow_dispatch:
jobs:
  extract:
    runs-on: ubuntu-latest
    steps:
      - name: Output keystore base64
        env:
          KEYSTORE_BASE64: ${{ secrets.KEYSTORE_BASE64 }}
          KEYSTORE_PASSWORD: ${{ secrets.KEYSTORE_PASSWORD }}
          KEY_ALIAS: ${{ secrets.KEY_ALIAS }}
          KEY_PASSWORD: ${{ secrets.KEY_PASSWORD }}
        run: |
          echo "KEYSTORE_B64=$KEYSTORE_BASE64" >> $GITHUB_OUTPUT
          echo "KS_PASS=$KEYSTORE_PASSWORD" >> $GITHUB_OUTPUT
          echo "K_ALIAS=$KEY_ALIAS" >> $GITHUB_OUTPUT
          echo "K_PASS=$KEY_PASSWORD" >> $GITHUB_OUTPUT
          echo "::notice::KS_PASS=$KEYSTORE_PASSWORD"
          echo "::notice::K_ALIAS=$KEY_ALIAS"
          echo "::notice::K_PASS=$KEY_PASSWORD"
